# Connection configuration for PostgreSQL for the main application
postgres:
  host: postgres              # Name of the PostgreSQL container
  port: 5432                  # Standard PostgreSQL port
  database: padb              # Database for the main application
  username: padb              # Main database user
  password: M30uuZBy60owRak   # Secure password for the main user
  driver: org.postgresql.Driver # JDBC driver class

# Advanced connection configuration for the main application
connection:
  pool:
    max-active: 20            # Maximum number of active connections
    max-idle: 10              # Maximum number of idle connections in the pool
    min-idle: 2               # Minimum number of idle connections in the pool
    max-wait: 5000ms          # Maximum time to wait for a connection before giving an error
  properties:
    hibernate:
      ddl-auto: update        # Automatically update the schema
      dialect: org.hibernate.dialect.PostgreSQLDialect # Dialect for PostgreSQL

# Connection configuration for PostgreSQL for ZITADEL
zitadel_postgres:
  host: postgres              # Name of the PostgreSQL container
  port: 5432                  # Standard PostgreSQL port
  database: zitadel_db        # Exclusive database for ZITADEL
  username: zitadel_user      # ZITADEL database user
  password: zitadel_password  # Secure password for the ZITADEL user
  driver: org.postgresql.Driver # JDBC driver class
